name: Wordmate Selenium Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Ejecutar tests diariamente a las 6:00 AM UTC
    - cron: '0 6 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
    
    - name: Run Selenium Tests
      run: |
        mvn clean test -Dheadless=true -Dbrowser=chrome -Dmaven.test.failure.ignore=true
      env:
        DISPLAY: :99
    
    - name: Generate Allure Report
      if: always()
      run: |
        mvn allure:report
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
            target/cucumber-reports/
            target/allure-results/
            target/site/allure-maven-plugin/
            retention-days: 30

    - name: Upload Screenshots
      if: failure()
      uses: actions/upload-artifact@v4 
      with:
        name: screenshots
        path: target/screenshots/
        retention-days: 7
    
    - name: Publish Test Results Summary
      if: always()
      run: |
        echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ -f target/cucumber-reports/cucumber-report.json ]; then
          echo "### Cucumber Test Results" >> $GITHUB_STEP_SUMMARY
          echo "📊 Test report generated successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "### Artifacts Generated" >> $GITHUB_STEP_SUMMARY
        echo "- 🥒 Cucumber HTML Report" >> $GITHUB_STEP_SUMMARY
        echo "- 📊 Allure Report" >> $GITHUB_STEP_SUMMARY
        echo "- 📄 JUnit XML Report" >> $GITHUB_STEP_SUMMARY
        
        if [ -d target/screenshots/ ] && [ "$(ls -A target/screenshots/)" ]; then
          echo "- 📸 Failure Screenshots" >> $GITHUB_STEP_SUMMARY
        fi